services:
  backend:
    image: courseflow-backend
    container_name: courseflow-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - SERVER_PORT=4000
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  frontend:
    image: courseflow-frontend
    container_name: courseflow-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
